steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull asia.gcr.io/$PROJECT_ID/GCR-APP:latest || exit 0']
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/GCR-APP', '--cache-from', 'asia.gcr.io/$PROJECT_ID/GCR-APP:latest', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/GCR-APP']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'GCR-APP', '--image', 'asia.gcr.io/$PROJECT_ID/GCR-APP', '--region', 'asia-southeast1', '--platform', 'managed', '--no-traffic', '--quiet']
images:
- asia.gcr.io/$PROJECT_ID/GCR-APP